// GENERATED by unity-ui-extract/tokens.py from cointoss-desktop.json
// Do not hand-edit: re-run the generator instead.

export const CANVAS = {
  refW: 1920,
  refH: 1080,
  match: 0.8,
  mode: "Expand",
} as const;

export const BACKDROP = {
    rect: {"x": 0, "y": 0, "w": 1920, "h": 1080},
    sprite: "backdrop-desktop",
    tint: "#FFFFFF",
  } as const;

export const NAV = {
    logo: { x: 244.5, y: 44, w: 211, h: 122 },
    balPanel: { x: 1247, y: 36, w: 434, h: 138 },
    balLabel: { x: 1298.2, y: 76.92, w: 121.84, h: 22.16, fs: 19.8 },
    currency: { x: 1298.2, y: 99.08, w: 63, h: 32, fs: 25.0 },
    value: { x: 1361.26, y: 99.08, w: 121.84, h: 32, fs: 25 },
    divider: { x: 1494.1, y: 80, w: 2, h: 50 },
    mode: { x: 1507.24, y: 93.92, w: 53.92, h: 22.16, fs: 9.75 },
    menuButton: { x: 1584, y: 86.5, w: 43, h: 37 },
    menuGlyph: { x: 1584, y: 86.5, w: 43, h: 37 },
  } as const;

export const COIN_VIEWPORT = { x: 258, y: 190, w: 700, h: 700 } as const;

export const STAKE_FIELD = {
    field: { x: 1068, y: 278, w: 680, h: 118.47 },
    input: { x: 1215, y: 298.06, w: 386, h: 59.51, fs: 36 },
    increase: { x: 1512.7, y: 278, w: 100, h: 100 },
    increaseGlyph: {"x": 1537.7, "y": 303, "w": 50, "h": 50},
    decrease: { x: 1203.3, y: 278, w: 100, h: 100 },
    decreaseGlyph: {"x": 1228.3, "y": 303, "w": 50, "h": 50},
    minimum: { x: 1078.74, y: 381.47, w: 300, h: 48, fs: 24 },
    maximum: { x: 1448, y: 381.47, w: 300, h: 48, fs: 24 },
  } as const;

export const CHIPS = {
    rowX: 1105.2,
    rowW: 605.5,
    rowH: 59.5,
    firstRowY: 466,
    secondRowY: 566,
    spacing: 23,
    w: 134.125,
    fs: 25,
  } as const;

export const CHOICE = {
    y: 679,
    h: 134.9,
    w: 274.75,
    headsX: 1105.2,
    tailsX: 1435.95,
    payFs: 20,
    payDy: 0.72,
    labelFs: 40,
    labelDy: 0.56,
    multiRoundBet: {"x": 1105.2, "y": 711, "w": 605.5, "h": 102.9, "fs": 36},
  } as const;

export const RESULTS = {
    trophy: {"x": 868, "y": 300, "w": 184, "h": 184},
    resultText: {"x": 610, "y": 500, "w": 700, "h": 80, "fs": 48},
    detailText: {"x": 610, "y": 590, "w": 700, "h": 60, "fs": 30},
    rebet: {"x": 1105.2, "y": 679, "w": 274.75, "h": 134.9, "fs": 40},
    newRound: {"x": 1435.95, "y": 679, "w": 274.75, "h": 134.9, "fs": 40},
  } as const;

export const CASHOUT_RETRY = {
    message: {"x": 610, "y": 420, "w": 700, "h": 120, "fs": 30},
    button: {"x": 810, "y": 560, "w": 300, "h": 100, "fs": 32},
  } as const;

export const MENU = {
    scrimAlpha: 0.6,
    close: { x: 448, y: 32, w: 96, h: 96, fs: 40 },
    closeGlyph: { x: 448, y: 32, w: 96, h: 96 },
    drawer: { x: 0, y: 0, w: 576, h: 1080 },
    rowX: 0,
    rowW: 576,
    rowH: 90,
    firstRowY: 150,
    rowPitch: 150,
    iconX: 48,
    iconSize: 56,
    iconDy: 17,
    lineX: 48,
    lineW: 480,
    lineDy: 89,
    textX: 128,
    textW: 360,
    textFs: 32,
    textDy: 20,
    arrowX: 488,
    arrowSize: 40,
    arrowDy: 25,
  } as const;

export const INSUFFICIENT = {
    card: { x: 600, y: 330, w: 720, h: 420 },
    header: {"x": 660, "y": 380, "w": 600, "h": 64, "fs": 42},
    body: {"x": 660, "y": 480, "w": 600, "h": 120, "fs": 32},
    close: {"x": 760, "y": 630, "w": 400, "h": 90, "fs": 32},
  } as const;

export const ERROR = {
    icon: {"x": 896, "y": 80, "w": 128, "h": 128},
    header: {"x": 560, "y": 230, "w": 800, "h": 64, "fs": 42},
    body: {"x": 560, "y": 300, "w": 800, "h": 80, "fs": 30},
    button: {"x": 810, "y": 300, "w": 300, "h": 90, "fs": 32},
  } as const;

export const TOAST = {
    panel: { x: 480, y: 64, w: 960, h: 108 },
    text: { x: 496, y: 72, w: 928, h: 92, fs: 32 },
  } as const;

export const LOADING = {
    holder: { x: 832, y: 412, w: 256, h: 256 },
    dotSize: 24,
    dots: [{"x": 948, "y": 438}, {"x": 1008, "y": 468}, {"x": 1038, "y": 528}, {"x": 1008, "y": 588}, {"x": 948, "y": 618}, {"x": 888, "y": 588}, {"x": 858, "y": 528}, {"x": 888, "y": 468}],
  } as const;

export const BET_HISTORY = {
    header: { x: 510, y: 64, w: 900, h: 64, fs: 42 },
    back: { x: 64, y: 42, w: 108, h: 108 },
    backGlyph: { x: 64, y: 42, w: 108, h: 108 },
    prev: { x: 32, y: 508, w: 64, h: 64 },
    next: { x: 1824, y: 508, w: 64, h: 64 },
    scroll: { x: 0, y: 276, w: 1920, h: 804 },
    emptyCard: { x: 0, y: 0, w: 1920, h: 1080 },
    emptyBug: {"x": 896, "y": 420, "w": 128, "h": 128},
    emptyTitle: {"x": 610, "y": 580, "w": 700, "h": 64, "fs": 42},
    emptySubtitle: {"x": 560, "y": 650, "w": 800, "h": 80, "fs": 30},
    headerRow: { x: 64, y: 160, w: 1792, h: 128 },
    outline: { x: 64, y: 150, w: 1792, h: 4 },
    rowH: 128,
    rowFs: 28,
    rowPitch: 132,
  } as const;

export const HELP = {
    header: { x: 510, y: 150, w: 900, h: 128, fs: 42 },
    back: { x: 1620, y: 152, w: 128, h: 128 },
    backGlyph: { x: 1620, y: 152, w: 128, h: 128 },
    body: { x: 128, y: 128, w: 1664, h: 952 },
    contentTop: 278,
    padX: 128,
    bodyFs: 30,
    bodyW: 1664,
  } as const;

export const KEYPAD = {
    scrim: { x: 0, y: 0, w: 1920, h: 1080 },
    body: { x: 672, y: 270, w: 576, h: 540 },
    display: { x: 736, y: 324, w: 448, h: 81 },
    input: { x: 740, y: 328, w: 440, h: 73 },
    inputText: { x: 772, y: 336, w: 266, h: 57, fs: 36 },
    backspace: { x: 1070, y: 328, w: 110, h: 73 },
    backspaceGlyph: { x: 1101, y: 340.5, w: 48, h: 48, fs: 32 },
    rowTops: [421.2, 491.4, 561.6, 631.8],
    keyLefts: [736, 890.6667, 1045.3333],
    keyW: 138.6667,
    keyH: 54.2,
    keyRowPadY: 8,
    keyFs: 32,
    save: { x: 736, y: 718, w: 448, h: 68, fs: 36 },
    close: { x: 1190.4, y: 270, w: 57.6, h: 54, fs: 40 },
    dot: {"x": 1110.67, "y": 662.9, "w": 8, "h": 8},
  } as const;

export const ORIENTATION = {
    icon: { x: 832, y: 412, w: 256, h: 256 },
    text: { x: 510, y: 790, w: 900, h: 180, fs: 36 },
  } as const;
